name: milton_app
description: A new Flutter project for Milton
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # জনপ্রিয় প্যাকেজগুলা
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets ফোল্ডার
  assets:
    - assets/images/
    - assets/icons/

  # Fonts লাগলে
  fonts:
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri-Regular.ttf
